export let user_main = [
    {
        id:100,
        nikname:'*Café Premium Gourmet',
	    name:'*En ésta preparación utilizamos exclusivamente cafés de exportación Estrictamente Duros (SHB); de los cuales obtenemos una sabor en taza con una acidez pronunciada, dulce delicado con un aroma intenso y un cuerpo completo.',	    
        adress:'*300g Stand- Pouch, con válvula desgasificadora y cierre-fácil. Incluye cuchara medidora 7 g.',	
        email:'*Precio detallista. Q32.85',	
        phone: '*Presentación Caja Master de 8 Unidades',
    },
    {
        id:101,
        nikname:'*Café Especial',
	    name:'*Esta preparación reúne las siguientes características: Tueste claro, sabor y aroma pronunciados, con una acidez leve; y un cuerpo medio.',	    
        adress:'*300g Stand- Pouch, con válvula desgasificadora y cierre-fácil. Incluye cuchara medidora 7 g.',	
        email:'*Precio detallista. Q21.20',	
        phone: '*Presentación Caja Master de 8 Unidades',
    },
    {
        id:102,
        nikname:'*Café Sabor Vainilla',
	    name:'*Este café presenta una armonía única entre el intenso sabor del café y el delicado sabor dulce de la vainilla, el digestivo ideal luego de una placentera comida.',	    
        adress:'*300g Stand- Pouch, con válvula desgasificadora y cierre-fácil. Incluye cuchara medidora 7 g.',	
        email:'*Precio detallista. Q22.8',	
        phone: '*Presentación Caja Master de 8 Unidades',  
    },
    {
        id:103,
        nikname:'*Café Sabor Canela',
	    name:'*Esta cuidadosa preparación une el sabor del café en perfecta armonía con la canela para ofrecer una nueva alternativa para disfrutar el café de la mañana o bien degustarlo acompañado de un postre. ',	    
        adress:'*300g Stand- Pouch, con válvula desgasificadora y cierre-fácil. Incluye cuchara medidora 7 g.',	
        email:'*Precio detallista. Q22.8',	
        phone: '*Presentación Caja Master de 8 Unidades',   
    },
    {
        id:104,
        nikname:'*Café Sabor Cardamomo',
	    name:'*Es una delicada combinación del pronunciado sabor del café con el intenso aroma del cardamomo, del cual resalta el sabor del café, percibiéndose un post gusto sutil a cardamomo. ',	    
        adress:'*300g Stand- Pouch, con válvula desgasificadora y cierre-fácil. Incluye cuchara medidora 7 g.',	
        email:'*Precio detallista. Q22.8',	
        phone: '*Presentación Caja Master de 8 Unidades',  
    },
    {
        id:105,
        nikname:'*Siropes',
	    name:'*Nuestros productos contienen saborizantes naturales, lo cual garantiza una mayor concentración de sabor.',	    
        adress:'*300g Stand- Pouch, con válvula desgasificadora y cierre-fácil. Incluye cuchara medidora 7 g.',	
        email:'*Botella de vidrio 750 ml.',	
        phone: '*Q79.95',   
    },
    {
        id:106,
        nikname:'*Salsas',
	    name:'*Las salsas no contienen saborizantes, colorantes, ni preservantes artificiales.',	    
        adress:'*300g Stand- Pouch, con válvula desgasificadora y cierre-fácil. Incluye cuchara medidora 7 g.',	
        email:'*Botella 16.5 Onz.',	
        phone: '*Q79.95',
    },
    {
        id:107,
        nikname:'*Modelo DELTA Versión de Lujo',
	    name:'*Cafetera Electrónica de erogación con dosaje volumétrico y Versión Manual.',	    
        adress:'*Versión 2 grupos , Grupo alto.',	
        email:'*Caldera con capacidad de 11 litros. ',	
        phone: '*$4,300.00',  
    }

]